server:
  servlet:
    context-path: /api
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:linkstation
    username: sa
    password:
    driverClassName: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show_sql: false
      format_sql: false
      ddl-auto: update
      default_schema: public